import { FitnessGoal, WorkoutLocation, ExperienceLevel, DaysPerWeek, WorkoutRoutine } from '../types';

export function generateWorkoutRoutines(
  goal: FitnessGoal,
  experience: ExperienceLevel,
  location: WorkoutLocation,
  days: DaysPerWeek
): WorkoutRoutine[] {
  // Customized routines according to location and goal
  const isHome = location === 'casa' || location === 'ar_livre';

  if (days <= 3) {
    // Full Body or ABC Split
    return [
      {
        id: 'routine-a',
        name: 'Treino A - Superior & Força',
        subtitle: 'Peito, Costas, Ombros e Braços',
        dayLabel: 'Treino 1 (Ex: Segunda-feira)',
        focus: goal === 'hipertrofia' ? 'Volume & Hipertrofia Superior' : 'Força & Ativação',
        estimatedMinutes: 45,
        exercises: isHome
          ? [
              {
                id: 'ex-1',
                name: 'Flexões de Braço (Push-ups)',
                muscleGroup: 'Peitoral & Tríceps',
                equipment: 'Peso Corporal',
                sets: [
                  { setNumber: 1, targetReps: '10-15', weightKg: 0 },
                  { setNumber: 2, targetReps: '10-15', weightKg: 0 },
                  { setNumber: 3, targetReps: 'Até a falha', weightKg: 0 },
                ],
                restSeconds: 60,
                notes: 'Mantenha o abdômen contraído e amplitude completa.',
              },
              {
                id: 'ex-2',
                name: 'Barra Fixa / Remada Invertida',
                muscleGroup: 'Costas & Bíceps',
                equipment: 'Barra ou Mesa firme',
                sets: [
                  { setNumber: 1, targetReps: '8-12', weightKg: 0 },
                  { setNumber: 2, targetReps: '8-12', weightKg: 0 },
                  { setNumber: 3, targetReps: '8-10', weightKg: 0 },
                ],
                restSeconds: 75,
                notes: 'Puxe focando em aproximar as escápulas.',
              },
              {
                id: 'ex-3',
                name: 'Desenvolvimento com Elástico / Halteres',
                muscleGroup: 'Ombros',
                equipment: 'Halteres ou Elástico',
                sets: [
                  { setNumber: 1, targetReps: '12-15', weightKg: 6 },
                  { setNumber: 2, targetReps: '12-15', weightKg: 6 },
                  { setNumber: 3, targetReps: '10-12', weightKg: 8 },
                ],
                restSeconds: 60,
              },
              {
                id: 'ex-4',
                name: 'Mergulho no Banco (Dips)',
                muscleGroup: 'Tríceps',
                equipment: 'Banco ou Cadeira firme',
                sets: [
                  { setNumber: 1, targetReps: '12-15', weightKg: 0 },
                  { setNumber: 2, targetReps: '12-15', weightKg: 0 },
                  { setNumber: 3, targetReps: '12-15', weightKg: 0 },
                ],
                restSeconds: 60,
              },
              {
                id: 'ex-5',
                name: 'Prancha Isométrica',
                muscleGroup: 'Abdômen & Core',
                equipment: 'Colchonete',
                sets: [
                  { setNumber: 1, targetReps: '45 seg', weightKg: 0 },
                  { setNumber: 2, targetReps: '45 seg', weightKg: 0 },
                  { setNumber: 3, targetReps: '60 seg', weightKg: 0 },
                ],
                restSeconds: 45,
              },
            ]
          : [
              {
                id: 'ex-1',
                name: 'Supino Reto com Barra ou Halteres',
                muscleGroup: 'Peitoral & Tríceps',
                equipment: 'Barra / Halteres',
                sets: [
                  { setNumber: 1, targetReps: '10-12', weightKg: 20 },
                  { setNumber: 2, targetReps: '8-10', weightKg: 25 },
                  { setNumber: 3, targetReps: '6-8', weightKg: 30 },
                  { setNumber: 4, targetReps: '8-10', weightKg: 25 },
                ],
                restSeconds: 90,
                notes: 'Foque na cadência controlada e amplitude completa.',
                personalRecordKg: 30,
              },
              {
                id: 'ex-2',
                name: 'Puxada Frontal na Polia (Lat Pulldown)',
                muscleGroup: 'Costas (Dorsais)',
                equipment: 'Polia Alta',
                sets: [
                  { setNumber: 1, targetReps: '10-12', weightKg: 40 },
                  { setNumber: 2, targetReps: '10-12', weightKg: 45 },
                  { setNumber: 3, targetReps: '8-10', weightKg: 50 },
                ],
                restSeconds: 75,
              },
              {
                id: 'ex-3',
                name: 'Desenvolvimento Militar com Halteres',
                muscleGroup: 'Ombros (Deltóides)',
                equipment: 'Halteres',
                sets: [
                  { setNumber: 1, targetReps: '10-12', weightKg: 12 },
                  { setNumber: 2, targetReps: '10-12', weightKg: 14 },
                  { setNumber: 3, targetReps: '8-10', weightKg: 16 },
                ],
                restSeconds: 75,
              },
              {
                id: 'ex-4',
                name: 'Remada Curvada com Barra',
                muscleGroup: 'Costas Médias',
                equipment: 'Barra',
                sets: [
                  { setNumber: 1, targetReps: '10-12', weightKg: 25 },
                  { setNumber: 2, targetReps: '8-10', weightKg: 30 },
                  { setNumber: 3, targetReps: '8-10', weightKg: 35 },
                ],
                restSeconds: 90,
              },
              {
                id: 'ex-5',
                name: 'Tríceps Corda na Polia',
                muscleGroup: 'Tríceps',
                equipment: 'Polia',
                sets: [
                  { setNumber: 1, targetReps: '12-15', weightKg: 20 },
                  { setNumber: 2, targetReps: '10-12', weightKg: 25 },
                  { setNumber: 3, targetReps: '10-12', weightKg: 25 },
                ],
                restSeconds: 60,
              },
              {
                id: 'ex-6',
                name: 'Rosca Direta com Halteres',
                muscleGroup: 'Bíceps',
                equipment: 'Halteres',
                sets: [
                  { setNumber: 1, targetReps: '10-12', weightKg: 10 },
                  { setNumber: 2, targetReps: '10-12', weightKg: 12 },
                  { setNumber: 3, targetReps: '8-10', weightKg: 12 },
                ],
                restSeconds: 60,
              },
            ],
      },
      {
        id: 'routine-b',
        name: 'Treino B - Membros Inferiores & Glúteos',
        subtitle: 'Quadríceps, Posterior, Glúteos e Panturrilhas',
        dayLabel: 'Treino 2 (Ex: Quarta-feira)',
        focus: 'Força e Construção das Pernas',
        estimatedMinutes: 50,
        exercises: isHome
          ? [
              {
                id: 'ex-b1',
                name: 'Agachamento Livre (Bodyweight Squat)',
                muscleGroup: 'Quadríceps & Glúteos',
                equipment: 'Peso Corporal',
                sets: [
                  { setNumber: 1, targetReps: '15-20', weightKg: 0 },
                  { setNumber: 2, targetReps: '15-20', weightKg: 0 },
                  { setNumber: 3, targetReps: '15-20', weightKg: 0 },
                  { setNumber: 4, targetReps: '20+', weightKg: 0 },
                ],
                restSeconds: 60,
              },
              {
                id: 'ex-b2',
                name: 'Afundo / Passada Alternada',
                muscleGroup: 'Pernas & Glúteos',
                equipment: 'Halteres ou Mochila',
                sets: [
                  { setNumber: 1, targetReps: '10 cada perna', weightKg: 0 },
                  { setNumber: 2, targetReps: '10 cada perna', weightKg: 5 },
                  { setNumber: 3, targetReps: '12 cada perna', weightKg: 5 },
                ],
                restSeconds: 60,
              },
              {
                id: 'ex-b3',
                name: 'Elevação Pélvica (Hip Thrust)',
                muscleGroup: 'Glúteos & Posterior',
                equipment: 'Sofá / Banco',
                sets: [
                  { setNumber: 1, targetReps: '15-20', weightKg: 0 },
                  { setNumber: 2, targetReps: '15', weightKg: 10 },
                  { setNumber: 3, targetReps: '15', weightKg: 10 },
                ],
                restSeconds: 60,
              },
              {
                id: 'ex-b4',
                name: 'Panturrilha Unilateral em Degrau',
                muscleGroup: 'Panturrilhas',
                equipment: 'Degrau',
                sets: [
                  { setNumber: 1, targetReps: '15-20', weightKg: 0 },
                  { setNumber: 2, targetReps: '15-20', weightKg: 0 },
                  { setNumber: 3, targetReps: '15-20', weightKg: 0 },
                ],
                restSeconds: 45,
              },
            ]
          : [
              {
                id: 'ex-b1',
                name: 'Agachamento Livre com Barra',
                muscleGroup: 'Quadríceps & Glúteos',
                equipment: 'Barra & Gaiola',
                sets: [
                  { setNumber: 1, targetReps: '10-12', weightKg: 30 },
                  { setNumber: 2, targetReps: '8-10', weightKg: 40 },
                  { setNumber: 3, targetReps: '6-8', weightKg: 50 },
                  { setNumber: 4, targetReps: '8-10', weightKg: 40 },
                ],
                restSeconds: 120,
                personalRecordKg: 50,
              },
              {
                id: 'ex-b2',
                name: 'Leg Press 45º',
                muscleGroup: 'Quadríceps & Glúteos',
                equipment: 'Máquina',
                sets: [
                  { setNumber: 1, targetReps: '12-15', weightKg: 100 },
                  { setNumber: 2, targetReps: '10-12', weightKg: 120 },
                  { setNumber: 3, targetReps: '10-12', weightKg: 140 },
                ],
                restSeconds: 90,
              },
              {
                id: 'ex-b3',
                name: 'Mesa Flexora / Cadeira Flexora',
                muscleGroup: 'Isquiotibiais (Posterior)',
                equipment: 'Máquina',
                sets: [
                  { setNumber: 1, targetReps: '12-15', weightKg: 35 },
                  { setNumber: 2, targetReps: '10-12', weightKg: 40 },
                  { setNumber: 3, targetReps: '10-12', weightKg: 45 },
                ],
                restSeconds: 60,
              },
              {
                id: 'ex-b4',
                name: 'Cadeira Extensora',
                muscleGroup: 'Quadríceps',
                equipment: 'Máquina',
                sets: [
                  { setNumber: 1, targetReps: '12-15', weightKg: 40 },
                  { setNumber: 2, targetReps: '12-15', weightKg: 45 },
                  { setNumber: 3, targetReps: '10-12 (Drop-set)', weightKg: 50 },
                ],
                restSeconds: 60,
              },
              {
                id: 'ex-b5',
                name: 'Elevação de Panturrilha em Pé',
                muscleGroup: 'Panturrilhas',
                equipment: 'Máquina / Degrau',
                sets: [
                  { setNumber: 1, targetReps: '15-20', weightKg: 40 },
                  { setNumber: 2, targetReps: '15-20', weightKg: 50 },
                  { setNumber: 3, targetReps: '15-20', weightKg: 50 },
                ],
                restSeconds: 45,
              },
            ],
      },
      {
        id: 'routine-c',
        name: 'Treino C - Full Body & Condicionamento',
        subtitle: 'Ativação metabólica, Core e Força funcional',
        dayLabel: 'Treino 3 (Ex: Sexta-feira)',
        focus: goal === 'emagrecer' ? 'Queima Calórica & HIIT' : 'Potência e Definição Total',
        estimatedMinutes: 40,
        exercises: [
          {
            id: 'ex-c1',
            name: 'Levantamento Terra (Deadlift) / Kettlebell Swing',
            muscleGroup: 'Cadeia Posterior & Lombar',
            equipment: isHome ? 'Halter ou Kettlebell' : 'Barra Olímpica',
            sets: [
              { setNumber: 1, targetReps: '10-12', weightKg: isHome ? 12 : 40 },
              { setNumber: 2, targetReps: '8-10', weightKg: isHome ? 16 : 50 },
              { setNumber: 3, targetReps: '6-8', weightKg: isHome ? 20 : 60 },
            ],
            restSeconds: 90,
          },
          {
            id: 'ex-c2',
            name: 'Elevação Lateral de Ombros',
            muscleGroup: 'Ombros Laterais',
            equipment: 'Halteres',
            sets: [
              { setNumber: 1, targetReps: '12-15', weightKg: 6 },
              { setNumber: 2, targetReps: '12-15', weightKg: 8 },
              { setNumber: 3, targetReps: '12-15', weightKg: 8 },
            ],
            restSeconds: 60,
          },
          {
            id: 'ex-c3',
            name: 'Abdominal Infra na Barra ou Colchonete',
            muscleGroup: 'Abdômen Inferior',
            equipment: 'Colchonete',
            sets: [
              { setNumber: 1, targetReps: '15-20', weightKg: 0 },
              { setNumber: 2, targetReps: '15-20', weightKg: 0 },
              { setNumber: 3, targetReps: '15-20', weightKg: 0 },
            ],
            restSeconds: 45,
          },
          {
            id: 'ex-c4',
            name: goal === 'emagrecer' || goal === 'condicionamento' ? 'Cardio HIIT (Esteira / Corda)' : 'Remada Unilateral (Serrote)',
            muscleGroup: goal === 'emagrecer' ? 'Cardiovascular' : 'Costas',
            equipment: goal === 'emagrecer' ? 'Esteira ou Corda' : 'Halter',
            sets: [
              { setNumber: 1, targetReps: goal === 'emagrecer' ? '5 min tiros' : '10-12 reps', weightKg: 0 },
              { setNumber: 2, targetReps: goal === 'emagrecer' ? '5 min tiros' : '10-12 reps', weightKg: isHome ? 10 : 16 },
              { setNumber: 3, targetReps: goal === 'emagrecer' ? '5 min tiros' : '8-10 reps', weightKg: isHome ? 12 : 20 },
            ],
            restSeconds: 60,
          },
        ],
      },
    ];
  }

  // 4 or 5-6 days: Push / Pull / Legs / Upper / Lower Split
  return [
    {
      id: 'routine-push',
      name: 'Treino A - Push (Empurrar)',
      subtitle: 'Peito, Ombros Anteriores/Laterais e Tríceps',
      dayLabel: 'Treino 1 (Ex: Segunda-feira)',
      focus: 'Peitoral e Tríceps',
      estimatedMinutes: 50,
      exercises: [
        {
          id: 'p-1',
          name: 'Supino Reto com Barra',
          muscleGroup: 'Peitoral Maior',
          equipment: 'Barra',
          sets: [
            { setNumber: 1, targetReps: '10-12', weightKg: 25 },
            { setNumber: 2, targetReps: '8-10', weightKg: 30 },
            { setNumber: 3, targetReps: '6-8', weightKg: 35 },
            { setNumber: 4, targetReps: '8-10', weightKg: 30 },
          ],
          restSeconds: 90,
          personalRecordKg: 35,
        },
        {
          id: 'p-2',
          name: 'Supino Inclinado com Halteres',
          muscleGroup: 'Peitoral Superior',
          equipment: 'Halteres & Banco Inclinado',
          sets: [
            { setNumber: 1, targetReps: '10-12', weightKg: 14 },
            { setNumber: 2, targetReps: '10-12', weightKg: 16 },
            { setNumber: 3, targetReps: '8-10', weightKg: 18 },
          ],
          restSeconds: 75,
        },
        {
          id: 'p-3',
          name: 'Desenvolvimento com Halteres',
          muscleGroup: 'Ombros (Deltóides)',
          equipment: 'Halteres',
          sets: [
            { setNumber: 1, targetReps: '10-12', weightKg: 12 },
            { setNumber: 2, targetReps: '10-12', weightKg: 14 },
            { setNumber: 3, targetReps: '8-10', weightKg: 16 },
          ],
          restSeconds: 75,
        },
        {
          id: 'p-4',
          name: 'Elevação Lateral na Polia ou Halteres',
          muscleGroup: 'Deltóide Lateral',
          equipment: 'Halteres / Polia',
          sets: [
            { setNumber: 1, targetReps: '12-15', weightKg: 7 },
            { setNumber: 2, targetReps: '12-15', weightKg: 8 },
            { setNumber: 3, targetReps: '12-15', weightKg: 8 },
          ],
          restSeconds: 60,
        },
        {
          id: 'p-5',
          name: 'Tríceps Testa com Barra W ou Halteres',
          muscleGroup: 'Tríceps (Cabeça Longa)',
          equipment: 'Barra W / Halteres',
          sets: [
            { setNumber: 1, targetReps: '10-12', weightKg: 15 },
            { setNumber: 2, targetReps: '10-12', weightKg: 18 },
            { setNumber: 3, targetReps: '8-10', weightKg: 20 },
          ],
          restSeconds: 60,
        },
        {
          id: 'p-6',
          name: 'Tríceps Corda na Polia',
          muscleGroup: 'Tríceps',
          equipment: 'Polia',
          sets: [
            { setNumber: 1, targetReps: '12-15', weightKg: 20 },
            { setNumber: 2, targetReps: '12-15', weightKg: 25 },
            { setNumber: 3, targetReps: '10-12', weightKg: 25 },
          ],
          restSeconds: 45,
        },
      ],
    },
    {
      id: 'routine-pull',
      name: 'Treino B - Pull (Puxar)',
      subtitle: 'Dorsais, Trapézio, Deltoide Posterior e Bíceps',
      dayLabel: 'Treino 2 (Ex: Terça-feira)',
      focus: 'Costas e Bíceps',
      estimatedMinutes: 50,
      exercises: [
        {
          id: 'pl-1',
          name: 'Puxada Frontal Aberta (Polia Alta)',
          muscleGroup: 'Dorsais',
          equipment: 'Polia',
          sets: [
            { setNumber: 1, targetReps: '10-12', weightKg: 40 },
            { setNumber: 2, targetReps: '10-12', weightKg: 45 },
            { setNumber: 3, targetReps: '8-10', weightKg: 50 },
            { setNumber: 4, targetReps: '8-10', weightKg: 55 },
          ],
          restSeconds: 75,
        },
        {
          id: 'pl-2',
          name: 'Remada Baixa com Triângulo',
          muscleGroup: 'Costas Médias',
          equipment: 'Polia Baixa',
          sets: [
            { setNumber: 1, targetReps: '10-12', weightKg: 40 },
            { setNumber: 2, targetReps: '10-12', weightKg: 45 },
            { setNumber: 3, targetReps: '8-10', weightKg: 50 },
          ],
          restSeconds: 75,
        },
        {
          id: 'pl-3',
          name: 'Crucifixo Inverso (Face Pull)',
          muscleGroup: 'Deltoide Posterior',
          equipment: 'Corda na Polia / Halteres',
          sets: [
            { setNumber: 1, targetReps: '12-15', weightKg: 20 },
            { setNumber: 2, targetReps: '12-15', weightKg: 25 },
            { setNumber: 3, targetReps: '12-15', weightKg: 25 },
          ],
          restSeconds: 60,
        },
        {
          id: 'pl-4',
          name: 'Rosca Direta com Barra W',
          muscleGroup: 'Bíceps',
          equipment: 'Barra W',
          sets: [
            { setNumber: 1, targetReps: '10-12', weightKg: 18 },
            { setNumber: 2, targetReps: '8-10', weightKg: 22 },
            { setNumber: 3, targetReps: '8-10', weightKg: 24 },
          ],
          restSeconds: 60,
        },
        {
          id: 'pl-5',
          name: 'Rosca Martelo com Halteres',
          muscleGroup: 'Braquial & Antebraço',
          equipment: 'Halteres',
          sets: [
            { setNumber: 1, targetReps: '10-12', weightKg: 10 },
            { setNumber: 2, targetReps: '10-12', weightKg: 12 },
            { setNumber: 3, targetReps: '10-12', weightKg: 12 },
          ],
          restSeconds: 60,
        },
      ],
    },
    {
      id: 'routine-legs',
      name: 'Treino C - Legs (Pernas Completas)',
      subtitle: 'Quadríceps, Isquiotibiais, Glúteos e Panturrilhas',
      dayLabel: 'Treino 3 (Ex: Quinta-feira)',
      focus: 'Membros Inferiores',
      estimatedMinutes: 55,
      exercises: [
        {
          id: 'lg-1',
          name: 'Agachamento Livre com Barra',
          muscleGroup: 'Quadríceps & Glúteos',
          equipment: 'Barra',
          sets: [
            { setNumber: 1, targetReps: '10-12', weightKg: 35 },
            { setNumber: 2, targetReps: '8-10', weightKg: 45 },
            { setNumber: 3, targetReps: '6-8', weightKg: 55 },
            { setNumber: 4, targetReps: '6-8', weightKg: 60 },
          ],
          restSeconds: 120,
          personalRecordKg: 60,
        },
        {
          id: 'lg-2',
          name: 'Leg Press 45º',
          muscleGroup: 'Pernas Completas',
          equipment: 'Máquina',
          sets: [
            { setNumber: 1, targetReps: '12-15', weightKg: 120 },
            { setNumber: 2, targetReps: '10-12', weightKg: 150 },
            { setNumber: 3, targetReps: '10-12', weightKg: 170 },
          ],
          restSeconds: 90,
        },
        {
          id: 'lg-3',
          name: 'Stiff com Barra ou Halteres',
          muscleGroup: 'Posterior de Coxa & Glúteos',
          equipment: 'Barra / Halteres',
          sets: [
            { setNumber: 1, targetReps: '10-12', weightKg: 25 },
            { setNumber: 2, targetReps: '10-12', weightKg: 30 },
            { setNumber: 3, targetReps: '8-10', weightKg: 35 },
          ],
          restSeconds: 90,
        },
        {
          id: 'lg-4',
          name: 'Cadeira Extensora',
          muscleGroup: 'Quadríceps',
          equipment: 'Máquina',
          sets: [
            { setNumber: 1, targetReps: '12-15', weightKg: 40 },
            { setNumber: 2, targetReps: '12-15', weightKg: 45 },
            { setNumber: 3, targetReps: '10-12', weightKg: 50 },
          ],
          restSeconds: 60,
        },
        {
          id: 'lg-5',
          name: 'Elevação de Panturrilhas Sentado / em Pé',
          muscleGroup: 'Panturrilhas',
          equipment: 'Máquina',
          sets: [
            { setNumber: 1, targetReps: '15-20', weightKg: 40 },
            { setNumber: 2, targetReps: '15-20', weightKg: 50 },
            { setNumber: 3, targetReps: '15-20', weightKg: 50 },
            { setNumber: 4, targetReps: '20+', weightKg: 40 },
          ],
          restSeconds: 45,
        },
      ],
    },
    {
      id: 'routine-core-cardio',
      name: 'Treino D - Ombros, Abdômen & Cardio',
      subtitle: 'Deltoides, Core Intenso e Queima Calórica',
      dayLabel: 'Treino 4 (Ex: Sexta-feira)',
      focus: 'Definição e Condicionamento',
      estimatedMinutes: 45,
      exercises: [
        {
          id: 'cc-1',
          name: 'Desenvolvimento Arnold com Halteres',
          muscleGroup: 'Ombros',
          equipment: 'Halteres',
          sets: [
            { setNumber: 1, targetReps: '10-12', weightKg: 12 },
            { setNumber: 2, targetReps: '10-12', weightKg: 14 },
            { setNumber: 3, targetReps: '8-10', weightKg: 14 },
          ],
          restSeconds: 75,
        },
        {
          id: 'cc-2',
          name: 'Elevação Frontal alternada com Halteres',
          muscleGroup: 'Deltoide Anterior',
          equipment: 'Halteres',
          sets: [
            { setNumber: 1, targetReps: '10-12 cada', weightKg: 8 },
            { setNumber: 2, targetReps: '10-12 cada', weightKg: 9 },
            { setNumber: 3, targetReps: '10-12 cada', weightKg: 9 },
          ],
          restSeconds: 60,
        },
        {
          id: 'cc-3',
          name: 'Prancha Abdominal com Toque nos Ombros',
          muscleGroup: 'Core e Estabilidade',
          equipment: 'Colchonete',
          sets: [
            { setNumber: 1, targetReps: '45 seg', weightKg: 0 },
            { setNumber: 2, targetReps: '45 seg', weightKg: 0 },
            { setNumber: 3, targetReps: '60 seg', weightKg: 0 },
          ],
          restSeconds: 45,
        },
        {
          id: 'cc-4',
          name: 'Abdominal Supra com Peso',
          muscleGroup: 'Abdômen',
          equipment: 'Anilha / Halter',
          sets: [
            { setNumber: 1, targetReps: '15-20', weightKg: 5 },
            { setNumber: 2, targetReps: '15-20', weightKg: 5 },
            { setNumber: 3, targetReps: '15-20', weightKg: 10 },
          ],
          restSeconds: 45,
        },
        {
          id: 'cc-5',
          name: 'Cárdio Metabólico (Esteira / Bike / Corda)',
          muscleGroup: 'Sistema Cardiovascular',
          equipment: 'Esteira ou Bike',
          sets: [
            { setNumber: 1, targetReps: '15 a 20 min contínuos ou HIIT', weightKg: 0 },
          ],
          restSeconds: 60,
        },
      ],
    },
  ];
}
